apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres
    app: demo-voter-app
spec:
  selector:
    name: postgres-pod
    app: demo-voter-app
  ports:
  - port: 5432
    targetPort: 5432
