apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo-voter-app
spec:
  selector:
    name: redis-pod
    app: demo-voter-app
  ports:
  - port: 6379
    targetPort: 6379
