apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voter-app-pod
    app: demo-voter-app
spec:
  containers:
  - name: voting-app
    image: kodekloud/examplevotingapp_vote:v1
    ports:
      - containerPort: 80
